input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.output {
	white-space: nowrap;
	margin-bottom: 20px;
}

.padded-row {
	margin-top: 15px;
	margin-bottom: 15px;
}

.force .input-sm {
	font-size: 20px;
	height: auto;
	margin-bottom: 2px;
	padding: 0px;
	white-space: normal;
}

.force .no-left-gutter {
	padding-left: 0px;
}
