<svg id="nCino_Icon_SVG" data-name="nCino Icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 391.96 310.12">
  <title>nCino</title>
  <g id="nCino_Icon_SVG_group">
    <rect x="105.24" y="81.36" width="76.25" height="228.75" fill="#85be40" />
    <rect y="159.66" width="76.25" height="150.45" fill="#0092c7" />
    <rect x="210.48" y="127.43" width="76.25" height="182.69" fill="#f1b643" />
    <rect x="315.71" width="76.25" height="310.12" fill="#ba202e" />
  </g>
</svg>