.selectize-control.single .selectize-input:after {
	border-style: none;
	border-width: none;
	border-color: none;
}
.selectize-control.single .selectize-input {
	background-color: #ffffff;
	background-image: none;
}
.selectize-dropdown, .selectize-input, .selectize-input input {
	font-size:12px;
}
.selectize-input {
	padding:0;
}
.selectize {
	width:400px;
}
.loadingSpinnerWidth {
	width: 40px !important;
}
.hiddenModal {
	display:none;
}
body {
  font-size: 14px !important;
}
